version: '3.9'

services:
  web:
    build: .
    command: bundle exec ruby app.rb -o 0.0.0.0 -p 4567
    volumes:
      - .:/app
    ports:
      - "${PORT_MAPPING}"
    environment:
      - APP_ENV=development
