services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rerun 'ruby app.rb -o 0.0.0.0 -p 4567' --
    volumes:
      - .:/app
    ports:
      - "${PORT_MAPPING}:4567"
    environment:
      - APP_ENV=development
